#!/bin/sh
#We have confirmed that MCR paths are correct
#source /home/mrsl/.bashrc
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/MATLAB/MCR/v81/runtime/glnxa64:/usr/local/MATLAB/MCR/v81/bin/glnxa64:/usr/local/MATLAB/MCR/v81/sys/os/glnxa64:/usr/local/MATLAB/MCR/v81/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/MCR/v81/sys/java/jre/glnxa64/jre/lib/amd64/server:/usr/local/MATLAB/MCR/v81/sys/java/jre/glnxa64/jre/lib/amd64
export XAPPLRESDIR=$XAPPLRESDIR:/usr/local/MATLAB/MCR/v81/X11/app-defaults

mscript="/home/mrsl/libs/bsTransmitGain $1"
$mscript








